package com.sweng.backend.highscore;

import jakarta.persistence.*;

/**
 * Entity representing a high score record in the system.
 *
 * <p>Each high score is uniquely associated with a username and stores the corresponding score
 * achieved by that user.
 */
@Entity
@Table(name = "highscores")
public class Highscore {

  /**
   * Unique identifier for the high score record.
   *
   * <p>Automatically generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * Username associated with the high score.
   *
   * <p>Must be unique and cannot be null.
   */
  @Column(nullable = false, unique = true)
  private String username;

  /**
   * Score achieved by the user.
   *
   * <p>Cannot be null.
   */
  @Column(nullable = false)
  private int score;

  /** Default constructor required by JPA. */
  public Highscore() {}

  /**
   * Constructs a high score record with the given username and score.
   *
   * @param username the username associated with the score
   * @param score the score achieved by the user
   */
  public Highscore(String username, int score) {
    this.username = username;
    this.score = score;
  }

  /**
   * Returns the unique identifier of this high score.
   *
   * @return the id of the high score
   */
  public Long getId() {
    return id;
  }

  /**
   * Returns the username associated with this high score.
   *
   * @return the username
   */
  public String getUsername() {
    return username;
  }

  /**
   * Sets the username for this high score.
   *
   * @param username the username to set
   */
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * Returns the score achieved by the user.
   *
   * @return the score
   */
  public int getScore() {
    return score;
  }

  /**
   * Sets the score for this high score.
   *
   * @param score the score to set
   */
  public void setScore(int score) {
    this.score = score;
  }
}
